controller:
    installPlugins:
    - configuration-as-code:1414.v878271fc496f
    - credentials-binding:1.27.1
    - branch-api:2.1044.v2c007e51b_87f
    - config-file-provider:3.9.0
    - ssh:2.6.1
    - envinject:2.4.0
    - environment-script:1.2.6
    - jobConfigHistory:2.30
    - rebuild:1.33.1
    - git:4.11.1
    - timestamper:1.17
    - job-dsl:1.79
    - workflow-aggregator:2.6
    - kubernetes:1.31.3
    - bouncycastle-api:2.26

    tag: 2.332.2

    JCasC:
      enabled: true
      configScripts:
        base-config: |
          jenkins:
            systemMessage: "Configured as Code"

          credentials:
            system:
              domainCredentials:
                - credentials:
                    - basicSSHUserPrivateKey:
                        scope: GLOBAL
                        id: jenkins-github-ssh
                        username:
                        passphrase:
                        description: "SSH key for GitHub"
                        privateKeySource:
                          directEntry:
                            privateKey: ${JENKINS_GITHUB_SSH}

          unclassified:
            globalConfigFiles:
              configs:
                - json:
                    id: auth-json
                    name: auth.json
                    comment: from jcasc
                    content: ${JENKINS_AUTH_JSON}

          jobs:
            - script: >
                job('super-seed') {
                  triggers {
                    // This trigger will be overwritten, it's just here to auto-trigger _one_ build.
                    cron('H/2 * * * *')
                  }
                  scm {
                    git {
                      remote {
                        url ('git@github.com:figaw/configuration-as-code-jenkins-k8s-jobdsl.git')
                        credentials('jenkins-github-ssh')
                      }
                    }
                  }
                  steps {
                    dsl {
                      external('jobdsl/**/*.groovy')
                      removeAction('DELETE')
                    }
                  }
                }

          security:
            globaljobdslsecurityconfiguration:
              useScriptSecurity: false

agent:
  image: figaw/jenkins-inbound-agent-gcloud
  tag: 4.10-3
